### PR TITLE
Fix bug with blocking request when ioloop already started

### PR DESCRIPTION
**Pull request by Logioniz**
When ioloop already started in "mojo app" request performed in non-blocking style. So, i fix this problem.

### CODE REVIEW

**Comment by Logioniz** [comment]
Now I found a bug in non-blocking mode

**Comment by jhthorsen** [comment]
Why do you need blocking mode support when the IOLoop is running?

I'm not going to take this pull request. The reason is that the solution is wrong: If you want to support blocking mode while the IOLoop is running, then you need to solve it differently. Something like:

```
if ($cb) {
  # run the code that already exists
}
else {
  # run a blocking code, without Mojo::IOLoop::Delay
}
```

**Comment by Logioniz** [comment]
I fix this bug about minute ago.

**Comment by jhthorsen** [comment]
But why do you need blocking mode? Running a blocking web request inside a Mojolicious application will block the whole application, and you have no control for how long. Why not do this:

```
get "/" => sub {
  my $c = shift;
  $c->delay(
    sub { $ua->$_request_with_digest_auth($method, $url, shift->begin) },
    sub {
      my ($delay, $tx) = @_;
      # ...
    },
  );
};
```

**Comment by Logioniz** [comment]
Because i write my current app in blocking mode.

**Comment by Logioniz** [comment]
Wait a minute, i add correct test for nonblocing mode

**Comment by Logioniz** [comment]
Previous test work too with my mistake in non-blocking mode. Now i improve test and previous incorrect solution not working.

**Comment by jhthorsen** [comment]
Calling `$ua->_start()` is also not allowed. It's a private method.

**Comment by Logioniz** [comment]
I know, but i not found better method.

**Comment by jhthorsen** [comment]
Please test "master". I will make a new release if that works for you.

**Comment by Logioniz** [comment]
Thanks, works. You may to add my test if you want to test this problem.

**Comment by jhthorsen** [comment]
Thank you for your effort :+1:

**Pull request closed without merging**
